# Generated by Django 5.2.4 on 2025-08-15 14:48

import apps.courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_slug_alter_course_category_and_more'),
        ('payments', '0002_rename_generated_at_paymentreceipt_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.CreateModel(
            name='RecordedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to=apps.courses.models.recorded_video_upload_path, validators=[apps.courses.models.validate_video_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_videos', to='courses.course')),
            ],
        ),
    ]
