"""
Django settings for kodetoCareer_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dj_database_url
from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q6n26th6r&(2n*b%1**n)7#$@ddy#fuxm9s1#kr0dm*ea!j*$2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = ['*']


# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
]

LOCAL_APPS = [
    'apps.accounts',
    'apps.courses',
    'apps.live_classes',
    'apps.assessments',
    'apps.payments',
    'apps.progress',
    'apps.certificates',
    'apps.notifications',
    'apps.common',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kodetoCareer_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kodetoCareer_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR}/db.sqlite3"
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
RAZORPAY_KEY_ID = 'rzp_test_ZI5G0k0dQJfr79'
RAZORPAY_KEY_SECRET = 'lZUttTsMhykdSWawNeXGC5nG'

# Optional: Webhook secret for signature validation
# You can get this from Razorpay dashboard when setting up webhooks
RAZORPAY_WEBHOOK_SECRET = 'Umrahchalo@786'  # Replace with actual secret

# Payment gateway settings
PAYMENT_GATEWAY_SETTINGS = {
    'RAZORPAY': {
        'KEY_ID': RAZORPAY_KEY_ID,
        'KEY_SECRET': RAZORPAY_KEY_SECRET,
        'WEBHOOK_SECRET': RAZORPAY_WEBHOOK_SECRET if 'RAZORPAY_WEBHOOK_SECRET' in locals() else None,
        'MODE': 'TEST',  # Change to 'LIVE' in production
    }
}

JITSI_DOMAIN = 'meet.jit.si'  
JITSI_APP_ID = None  # Your Jitsi app ID (optional)
JITSI_APP_SECRET = None
LANGUAGE_CODE = 'en-us'
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.CustomPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://kodetocareer.com",
    "https://www.kodetocareer.com",
    "https://kodetocareer.in",
    "https://www.kodetocareer.in",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# CSRF trusted domains (important for forms, login, payments)
CSRF_TRUSTED_ORIGINS = [
    "https://kodetocareer.com",
    "https://www.kodetocareer.com",
    "https://kodetocareer.in",
    "https://www.kodetocareer.in",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]



# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST ='smtp.gmail.com',
EMAIL_PORT = 587,
EMAIL_USE_TLS =True,
EMAIL_HOST_USER ='tatasalt431@gmail.com',
EMAIL_HOST_PASSWORD ='fubpsexmiwyexpaf'

# Payment Gateway Settings
RAZORPAY_KEY_ID = 'RAZORPAY_KEY_ID',
RAZORPAY_KEY_SECRET ='RAZORPAY_KEY_SECRET',
STRIPE_PUBLISHABLE_KEY = 'STRIPE_PUBLISHABLE_KEY',
STRIPE_SECRET_KEY ='STRIPE_SECRET_KEY',
# Custom User Model
AUTH_USER_MODEL = 'accounts.User'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
