# Generated by Django 5.2.4 on 2025-07-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
