# Generated by Django 5.2.4 on 2025-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0002_alter_liveclass_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('zoom', 'Zoom'), ('jitsi', 'Jitsi Meet'), ('google_meet', 'Google Meet'), ('custom', 'Custom Platform')], max_length=20),
        ),
    ]
