# Generated by Django 5.2.4 on 2025-08-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0003_alter_liveclass_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
